INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Bread', 50);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Milk', 90);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Eggs', 120);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Juice', 180);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Meat', 390);
